googleAnalytics = "G-T6RJY7HY09"
baseURL = 'https://www.studiomystery.com'
languageCode = 'en-us'
title = 'Studio Mystery'
theme = 'hugo-book'
[params]
    # BookTheme = 'dark'
    BookSection = '*'
    BookLogo = '/images/favicon.png'
    BookFavicon = '/images/favicon.png'
